# Setup
title: pichot.us
url: https://pichot.us
baseurl: ""
permalink: /:year/:title/

# Collections
collections:
  projects:
    output: true
    

# Gems
plugins:
  # - jekyll-gist
  # - jekyll-paginate-v2
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - functions

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Jonathan Pichot
  url: https://twitter.com/_twitter
  email: jonathan@pichot.us
